### ISSUE TITLE
Train/dev split

### ISSUE THREAD

**Issue by ZhaofengWu** [DreamerDeo/HIT-SCIR-CoNLL2019#12]
In your config there appears a dev set
https://github.com/DreamerDeo/HIT-SCIR-CoNLL2019/blob/903d16bd9949eaf1e350fbcc7e0ff28ea00f985d/config/transition_bert_sdp_conll.jsonnet#L28
Do you mind sharing how you split the dev set from the original dataset? I couldn't find relevant details in your paper. Sorry if I missed anything.

**Comment by DreamerDeo** [comment]
Hi, I have upload the spilt dataset (from original train data). [https://drive.google.com/file/d/13YbfqP05Vn8aKnwcDQwZ4FWY6hR6qZaB/view?usp=sharing](https://drive.google.com/file/d/13YbfqP05Vn8aKnwcDQwZ4FWY6hR6qZaB/view?usp=sharing)

**Comment by longxudou** [comment]
Hi,

Based on mrp2019 website, I didn't get a clear response on whether the original dataset is allowed to release by third-party instead of LDC. Therefore. I extract the ids from split data and upload these ids files in google drive [https://drive.google.com/file/d/1U85ZeHOcSH6lQAhlznAhO4faFdJs42ct/view?usp=sharing](https://drive.google.com/file/d/1U85ZeHOcSH6lQAhlznAhO4faFdJs42ct/view?usp=sharing).

Like the following ids in amr_dev:
```
col_1015.16
PROXY_AFP_ENG_20070529_0077.15
bolt-eng-DF-170-181122-8789911_0067.6
bolt-eng-DF-170-181103-8886574_0333.17
DF-200-192448-618_9563.7
DF-170-181104-872_5719.4
```

**Comment by ZhaofengWu** [comment]
Thanks! This is very helpful.
