### ISSUE TITLE
KeyError when Evaluation on UCCA parser 

### ISSUE THREAD

**Issue by ccclyu** [DreamerDeo/HIT-SCIR-CoNLL2019#3]
Hi, thanks for sharing the code. Great work!

When I run on your released models in the Google drive to evaluate  the UCCA , I met with a problem shown in the below error message, which might be a bug. Could you please help me check about it?  Really appreciate.

1. First I covert the evaluation data in **input.mrp** using script **toolkit/preprocess_eval.py** and generate the file **ucca.mrp**.  
2. Use **predict.sh** to evaluate the ucca.mrp.  The error message showed that 

> File "./utils/transition_ucca_reader.py", line 407, in _read(self, file_path: str)
    arc_indices = ret["arc_indices"] 
    KeyError: 'arc_indices'

https://github.com/DreamerDeo/HIT-SCIR-CoNLL2019/blob/db9bd12fe560502b1ede9e91dfd1895a77e105cb/utils/transition_ucca_reader.py#L399

https://github.com/DreamerDeo/HIT-SCIR-CoNLL2019/blob/db9bd12fe560502b1ede9e91dfd1895a77e105cb/utils/transition_ucca_reader.py#L407

After I track back the function call, the issue should be in the line **152-165** of the same file 

```python
   ###Step 1: Extract surface token node
   ### MRP-Testing mode: tokenization from Companion data
   if self.testing == True and len(self.companion) != 0:
       token_info = self.extract_token_info_from_companion_data()
       tokens = token_info["tokens"]
       token_range = token_info["token_range"]
       self.lay_0_node = token_info["tokens"]

       ret = {"tokens": tokens,
                 "tokens_range": token_range,
                  "layer_0_node": self.lay_0_node,
                  "meta_info": self.meta_info}
       return ret
```

So when using the way as step 1 to tokenization from Companion  data, the resulted dict *ret* has no member such as *arc_indices*, *arc_tags* in line 275, which leads to the above error. Could you please how to resolve the issues and run the evaluations for ucca parser? 

Thanks for your time again!

***one example of the "ucca.mrp"***: 

{"id": "103780", "flavor": 1, "framework": "ucca", "version": 1.0, "time": "2019-07-15", "input": "She adjusted her petals one by one.", "tops": [1], "companion": [["1", "She", "she", "PRO     N", "PRP", "_", "2", "nsubj", "_", "TokenRange=0:3"], ["2", "adjusted", "adjust", "VERB", "VBD     ", "_", "_", "_", "_", "TokenRange=4:12"], ["3", "her", "she", "PRON", "PRP$", "_", "4", "nmod:poss", "_", "TokenRange=13:16"], ["4", "petals", "petal", "NOUN", "NNS", "_", "2", "obj", "_"     , "TokenRange=17:23"], ["5", "one", "one", "NUM", "CD", "_", "2", "obj", "_", "TokenRange=24:2     7"], ["6", "by", "by", "ADP", "IN", "_", "7", "case", "_", "TokenRange=28:30"], ["7", "one", "     one", "NUM", "CD", "_", "5", "nmod", "_", "TokenRange=31:34"], ["8", ".", ".", "PUNCT", ".", "     _", "2", "punct", "_", "TokenRange=34:35"]]}

**Comment by longxudou** [comment]
Hi, thank you for your interest in our work.

I have fixed the bug and upload the code.
In evaluation data, gold graphs are not available. It only provides the sentence, anchor information and pos-tag. Thus, We need set the gold actions be `none` in `reader.py` and let it be the signal to skip some steps in parser, such as computing the mrp score.

**Comment by ccclyu** [comment]
Thanks greatly for your prompt help ! Also a quick question for the final evaluation: does the **quality of Companion data**  i.e., the universal parsing of test sentences,  affect the final prediction or what the extend of the effect in your experiments?  

I know currently the organizer already provided the parsed data and just discuss for the potential errors or any insight when you participate the contest ？Thanks~

**Comment by longxudou** [comment]
1)In our preliminary experiments, our model didn't benefit a lot from pos-tag and lemma which contained in companion data, i.e predicted by UD Pipe model. We think it's because it's not gold label. Thus we didn't use those two information. Only the anchor information is adopted for computing the node bound. Even for DM/PSD, the label and pos label are predicted by two taggers which are trained with the parser.

2)For the second question, we have tried some methods for cross-framework parsing such multi-task learning among distinct tasks, transfer learning. However, we didn't get a non-trival conclusions. In my personal view, I thought the 'really' unified framework for broad-coverage semantic parsing is untouchable which make sense from both the linguistic and ML view.
It's more easier for us to adopt the advanced pre-trained NLP model (BERT) or powerful module (Transformer) to improve the ability of parser.

Based on the experiments on SDP, we found that powerful representation could eliminate the gap between structure or parsing strategy. More details are listed in [our paper].(https://www.aclweb.org/anthology/K19-2007.pdf)

**Comment by ccclyu** [comment]
Really appreciate your sharing of experiences and insights !  In other words,  powerful contextual representations such as BERT have already somehow encoded such semantic information as long as the Transformer structures could attend longer distances. Maybe some probe tasks could be designed to detect the semantic encoding ability.   I would close the issue currently and re-open if I meet problems. Thanks!

**Comment by ZhaofengWu** [comment]
Following up on this, just want to make sure my understanding is correct: during both training and evaluation, the only thing you took from the companions is the tokenization, correct?

EDIT: re-raised in #6
