### ISSUE TITLE
Why do different frameworks use different flavors of BERT?

### ISSUE THREAD

**Issue by ZhaofengWu** [DreamerDeo/HIT-SCIR-CoNLL2019#4]
Thanks for the amazing repo! I have some quick questions: according to the readme

> DM/PSD/UCCA/EDS use cased_L-12_H-768_A-12 (`cased-bert-base`) and AMR uses wwm_cased_L-24_H-1024_A-16 (`wwm-cased-bert-large`).

Why does only AMR use (1) wwm, and (2) the large model? Would the other formalism also benefit from at least a larger model? Also, have you tried the more recent pretrained transformers, e.g. RoBERTa? (The AllenNLP master version (or the soon-to-be-released 1.0 version) contains improvements that allow very easy experimentation with different types of pretrained transformers.)

**Comment by longxudou** [comment]
Hi, thank you for your interest in our work!

Because of time and resource constraints, we only tried these two pretrained models during the conll2019. The AMR part is finished by @franklear, and he found the AMR parser benefit from wwm-cased-bert-large. However, in preliminary experiments, I didn't find significant improvement during the development of DM/PSD/UCCA/EDS with the large bert, and it's training unstably.

Moreover, we use the default parameters used in BERT literature. I believe you could reach a better performance via 1)adopting large model and 2)carefully fine-tuning the model hyper-parameters.

We will continue working on this project during conll2020 and try different types of pretrained transformers as you said.

Best,
Longxu

**Comment by ZhaofengWu** [comment]
I see. Thanks for sharing the insights!
